# Generated by Django 5.2.9 on 2025-12-17 05:16

import django.contrib.postgres.fields
import django.db.models.deletion
import summaries.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_code', models.CharField(db_index=True, default=summaries.models.generate_share_code, max_length=8, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('markdown', models.TextField()),
                ('key_points', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=16)),
                ('word_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_summaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_summaries', to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='summaries.summary')),
            ],
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['share_code'], name='summaries_s_share_c_367427_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsummary',
            unique_together={('user', 'summary')},
        ),
    ]
