# Generated by Django 5.2.9 on 2025-12-20 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuotaBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('general', 'General AI'), ('quiz', 'Quiz AI')], max_length=32)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_credits', models.PositiveIntegerField(default=0)),
                ('max_credits', models.PositiveIntegerField()),
                ('window_hours', models.PositiveSmallIntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'bucket'], name='ai_aiquotab_user_id_c60548_idx')],
                'unique_together': {('user', 'bucket')},
            },
        ),
    ]
