# Generated by Django 5.2.9 on 2025-12-22 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('feedback_type', models.CharField(choices=[('rating', 'Rating'), ('bug', 'Bug'), ('suggestion', 'Suggestion')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['feedback_type'], name='feedback_fe_feedbac_ba1d78_idx'), models.Index(fields=['user', 'feedback_type'], name='feedback_fe_user_id_22e651_idx')],
            },
        ),
    ]
